#!/bin/bash

mysql -u root -p -e "DROP DATABASE IF EXISTS project2"
mysql -u root -p  -e "CREATE DATABASE project2"
mysql -u root -p project2 < ../database/project2.sql
mysql -u root -p -e "DROP USER IF EXISTS tester"
mysql -u root -p -e "CREATE USER 'tester'@'%' IDENTIFIED BY 'Project2!'"
mysql -u root -p -e "GRANT SELECT ON project2.* TO 'tester'@'%'"

